
- name: Deploying Haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Copying files
  synchronize: src=../files/ dest=/

- name: Chmodding the certificates directory
  file: path=/etc/haproxy/certs owner=root group=root mode=0700 state=directory

- name: Chmodding the files
  shell: "find /etc/haproxy/certs -type f -exec chmod 0600 {} \\;"

- name: Reloading HAProxy
  service: name=haproxy state=reloaded
