---
- name: Create the network
  os_network: name="DemoNetwork" state=present
  register: demo_network

- name: Create the subnet
  os_subnet:
    name: "DemoSubnet"
    network_name: "{{ demo_network.network.name }}"
    cidr: "{{ net_cidr }}"
    dns_nameservers:
       - 8.8.8.8
       - 8.8.4.4
    state: present

- name: Create the router
  os_router:
    name: "DemoRouter"
    network: "PublicNetwork"
    interfaces: [ "DemoSubnet" ]
    state: present
